# Anything that goes here is made globally for all profiles.
spring:
  application:
    name: capybaras-fems
    post-crud:
      POST_URL: http://10.115.6.117


POST_URL: 10.115.6.117

---
# Anything that goes here is made specifically for clouds's profile.
# Cloud is the default profile that Google Clound Foundry makes your application use if you do not override it.
spring:
  profiles: cloud, default

server:
  port: 8080
  postCrud:
    POST_URL: http://10.115.6.117

---
# Anything that goes here is made specifically for local's profile.
spring:
  profiles: local

server:
  port:

